[package]
name = "specs-hierarchy"
version = "0.6.1"
authors = ["Aceeri <conmcclusk@gmail.com>", "Rhuagh <seamonr@gmail.com>"]
repository = "https://github.com/rustgd/specs-hierarchy.git"
homepage = "https://github.com/rustgd/specs-hierarchy.git"

license = "MIT/Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/specs-hierarchy"
description = "Scene graph type hierarchy abstraction for use with specs"

keywords = ["specs", "scenegraph", "hierarchy"]

[dependencies]
hibitset = { version = "0.6.3", default-features = false }
#specs = { rev = "0.16.1", default-features = false, features = ["shred-derive"] }
specs = { git = "https://github.com/adamnemecek/specs", rev = "49224e6", features = ["shred-derive"]  }
shrev = "1.1.1"

[features]
default = ["parallel"]
parallel = ["specs/parallel", "hibitset/parallel"]
